#!/bin/bash
set -euo pipefail

JSON_FILE="/etc/asterisk/rcm_ring_groups.json"
TARGET="/etc/asterisk/extensions_gui.conf"

need(){ command -v "$1" >/dev/null 2>&1 || { echo "ERROR: missing $1"; exit 1; }; }
need jq

if [[ ! -f "$JSON_FILE" ]]; then
  echo "ERROR: $JSON_FILE not found"
  exit 1
fi
if [[ ! -f "$TARGET" ]]; then
  echo "ERROR: $TARGET not found"
  exit 1
fi

# ensure markers exist
if ! grep -q '^; RCM-RG-START' "$TARGET"; then
  printf '\n; RCM-RG-START\n[rcm-ring-groups]\n; RCM-RG-END\n' >>"$TARGET"
fi
if ! grep -q '^; RCM-RG-END' "$TARGET"; then
  echo "ERROR: RCM-RG-END marker missing in $TARGET"
  exit 1
fi

ROOT=$(jq -c '
  if type=="object" and (.groups|type=="array") then .
  elif type=="array" then {groups:.}
  else {groups:[]}
  end
' "$JSON_FILE")

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "; RCM-RG-START"
  echo "[rcm-ring-groups]"
  echo "; AUTOGENERATED from $JSON_FILE"
  echo "; Generated: $(date -Is)"
  echo

  echo "$ROOT" | jq -c '.groups[]? | select(.enabled != false)' | while read -r g; do
    gid=$(jq -r '.id // ""' <<<"$g")
    name=$(jq -r '.name // ""' <<<"$g")
    strategy=$(jq -r '.strategy // "ringall"' <<<"$g")
    timeout=$(jq -r '.timeout // 20' <<<"$g")
    per_try=$(jq -r '.per_try // 15' <<<"$g")
    mapfile -t members < <(jq -r '.members[]? // empty' <<<"$g" | sed '/^$/d')

    [[ -z "$gid" ]] && continue
    [[ ${#members[@]} -eq 0 ]] && continue
    [[ "$timeout" =~ ^[0-9]+$ ]] || timeout=20
    [[ "$per_try" =~ ^[0-9]+$ ]] || per_try=15

    echo "exten => ${gid},1,NoOp(RCM-RG id=${gid} name=${name} strategy=${strategy})"

    if [[ "$strategy" == "ordered" ]]; then
      for m in "${members[@]}"; do
        echo " same => n,Dial(PJSIP/${m},${per_try},Tt)"
        echo " same => n,GotoIf(\$[\"\${DIALSTATUS}\"=\"ANSWER\"]?done)"
      done
      echo " same => n(done),Hangup()"
    else
      dialstr=""
      for m in "${members[@]}"; do
        if [[ -z "$dialstr" ]]; then dialstr="PJSIP/${m}"; else dialstr="${dialstr}&PJSIP/${m}"; fi
      done
      echo " same => n,Dial(${dialstr},${timeout},Tt)"
      echo " same => n,Hangup()"
    fi

    echo
  done

  echo "; RCM-RG-END"
} >"$TMP"

# replace block between markers
perl -0777 -i -pe 's/; RCM-RG-START.*?; RCM-RG-END/'"$(perl -pe 's/[\/&]/\\$&/g' "$TMP" | tr "\n" "\\n")"'/s' "$TARGET"

# fix newlines escaped by perl trick (convert \n back)
perl -i -pe 's/\\n/\n/g' "$TARGET"

echo "OK: generated ring groups into $TARGET"
