#!/bin/bash
set -euo pipefail

JSON="/etc/asterisk/rcm_ring_groups.json"
OUT="/etc/asterisk/rcm_ring_groups.conf"
TMP="$(mktemp)"

need(){ command -v "$1" >/dev/null 2>&1 || { echo "ERROR: missing $1"; exit 1; }; }
need jq
need date

[[ -f "$JSON" ]] || { echo "ERROR: $JSON not found"; exit 1; }

ROOT="$(jq -c '
  if type=="object" and (.groups|type=="array") then .
  elif type=="array" then {groups:.}
  else {groups:[]}
  end
' "$JSON")"

{
  echo "; =============================="
  echo "; RCM RING GROUPS"
  echo "; AUTOGENERATED - DO NOT EDIT"
  echo "; Source: $JSON"
  echo "; Generated: $(date -Iseconds)"
  echo "; =============================="
  echo ""
  echo "; RCM-RG-START"
  echo "[rcm-ring-groups]"
  echo "; AUTOGENERATED from $JSON"
  echo ""

  # لكل جروب enabled=true
  echo "$ROOT" | jq -c '.groups[]? | select(.enabled != false)' | while IFS= read -r g; do
    id="$(jq -r '.id // ""' <<<"$g")"
    name="$(jq -r '.name // ""' <<<"$g")"
    strat="$(jq -r '.strategy // "ringall"' <<<"$g")"
    timeout="$(jq -r '.timeout // 20' <<<"$g")"
    per_try="$(jq -r '.per_try // 10' <<<"$g")"

    # normalize id
    id="$(echo "$id" | tr -d '[:space:]')"
    [[ -n "$id" ]] || continue

    # members as array of strings (preserve order)
    mapfile -t members < <(jq -r '.members[]? // empty | tostring' <<<"$g" | sed 's/[^0-9]//g' | awk 'NF')
    # remove duplicates while preserving order
    if ((${#members[@]} > 0)); then
      uniq=()
      seen=""
      for m in "${members[@]}"; do
        [[ -z "$m" ]] && continue
        if ! grep -qxF "$m" <<<"$seen" 2>/dev/null; then
          uniq+=("$m")
          seen+="$m"$'\n'
        fi
      done
      members=("${uniq[@]}")
    fi

    echo "exten => $id,1,NoOp(RCM-RG id=$id name=$name strategy=$strat)"
    if ((${#members[@]} == 0)); then
      echo " same => n,Playback(invalid)"
      echo " same => n,Hangup()"
      echo ""
      continue
    fi

    # ringall
    if [[ "$strat" == "ringall" ]]; then
      dial=""
      for m in "${members[@]}"; do
        if [[ -z "$dial" ]]; then dial="PJSIP/$m"; else dial="$dial&PJSIP/$m"; fi
      done
      # timeout = كامل الرن
      echo " same => n,Dial($dial,$timeout,Tt)"
      echo " same => n,Hangup()"
      echo ""
      continue
    fi

    # ordered (sequential)
    # كل محاولة per_try ثواني
    for m in "${members[@]}"; do
      echo " same => n,Dial(PJSIP/$m,$per_try,Tt)"
      echo " same => n,GotoIf(\$[\"\${DIALSTATUS}\"=\"ANSWER\"]?done)"
    done
    echo " same => n(done),Hangup()"
    echo ""
  done

  echo "; RCM-RG-END"
  echo ""
} >"$TMP"

install -m 0644 "$TMP" "$OUT"
rm -f "$TMP"

echo "OK: generated $OUT"
