#include pjsip.endpoint.conf
#include pjsip.auth.conf
#include pjsip.aor.conf
#include pjsip.reg.conf
#include pjsip.identify.conf


; --- GUI PJSIP (Added from Web) ---
#include pjsip.gui.endpoint.conf
#include pjsip.gui.auth.conf
#include pjsip.gui.aor.conf
#include pjsip.gui.identify.conf
#include pjsip.gui.reg.conf




[global]
type=global
endpoint_identifier_order=username,auth_username,ip

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5080



;[transport-tls]
;type=transport
;protocol=tls
;bind=0.0.0.0:5162
;cert_file=/etc/asterisk/keys/asterisk.crt
;priv_key_file=/etc/asterisk/keys/asterisk.key
;method=tlsv1_2
;verify_client=no
;verify_server=no





