#include pjsip.endpoint.conf
#include pjsip.auth.conf
#include pjsip.aor.conf
#include pjsip.reg.conf
#include pjsip.identify.conf


; --- GUI PJSIP (Added from Web) ---
#include pjsip.gui.endpoint.conf
#include pjsip.gui.auth.conf
#include pjsip.gui.aor.conf
#include pjsip.gui.identify.conf
#include pjsip.gui.reg.conf




[global]
type=global
endpoint_identifier_order=username,auth_username,ip

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5080



;[transport-tls]
;type=transport
;protocol=tls
;bind=0.0.0.0:5061
;cert_file=/etc/asterisk/keys/asterisk.crt
;priv_key_file=/etc/asterisk/keys/asterisk.key
;method=tlsv1_2
;verify_client=no
;verify_server=no


[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
cert_file=/etc/asterisk/keys/asterisk.crt
priv_key_file=/etc/asterisk/keys/asterisk.key
method=tlsv1_2
verify_client=no
verify_server=no
ca_list_file=
external_signaling_address=154.176.161.185
external_media_address=154.176.161.185

[twilio-auth]
type=auth
auth_type=userpass
username=fiberme
password=FiberMEP@ssw0rd

[twilio-trunk]
type=registration
transport=transport-tls
outbound_auth=twilio-auth
server_uri=sip:rafik.pstn.twilio.com:5061
client_uri=sip:fiberme@rafik.pstn.twilio.com
contact_user=fiberme
line=yes
endpoint=twilio-endpoint
retry_interval=60

[twilio-endpoint]
type=endpoint
transport=transport-tls
context=from-twilio
disallow=all
allow=ulaw
allow=alaw
outbound_auth=twilio-auth
aors=twilio-aor
from_user=fiberme
from_domain=rafik.pstn.twilio.com
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[twilio-aor]
type=aor
contact=sip:rafik.pstn.twilio.com:5061;transport=tls

[twilio-identify]
type=identify
endpoint=twilio-endpoint
match=54.172.60.0/23
match=54.244.51.0/24
match=54.171.127.192/26




