; --- RCM-TRUNK: test BEGIN ---
[test_identify]
type=identify
endpoint=test
match=192.168.22.22
; --- RCM-TRUNK: test END ---

; --- RCM-TRUNK: www BEGIN ---
[www_identify]
type=identify
endpoint=www
match=ww
; --- RCM-TRUNK: www END ---
