; --- RCM-TRUNK: FAG4108 BEGIN ---
[FAG4108_identify]
type=identify
endpoint=FAG4108
match=192.168.99.170
; --- RCM-TRUNK: FAG4108 END ---

; --- RCM-TRUNK: test BEGIN ---
[test_identify]
type=identify
endpoint=test
match=192.168.22.22
; --- RCM-TRUNK: test END ---

; --- RCM-TRUNK: www BEGIN ---
[www_identify]
type=identify
endpoint=www
match=ww
; --- RCM-TRUNK: www END ---

; --- RCM-TRUNK: UCM BEGIN ---
[UCM_identify]
type=identify
endpoint=UCM
match=192.168.99.5
; --- RCM-TRUNK: UCM END ---
