[5000]
max_contacts=10
remove_existing=yes
qualify_frequency=60
type=aor


[5001]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60


[5002]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60


[5003]
max_contacts=10
remove_existing=yes
qualify_frequency=60
type=aor


[5004]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60
[9999]
type=aor
max_contacts=9666
remove_existing=yes
qualify_frequency=60


[5858]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60
[2121]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60


[3001]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60


[555]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60


[10000]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60

; --- RCM-TRUNK: GSM BEGIN ---
[GSM]
type=aor
contact=sip:192.168.99.237:5060
qualify_frequency=60
; --- RCM-TRUNK: GSM END ---
