[5000]
max_contacts=10
remove_existing=yes
qualify_frequency=60
type=aor


[5001]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60


[5002]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60


[5003]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60


[5004]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60
; --- RCM-TRUNK: 6363 BEGIN ---
[6363]
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=60
; --- RCM-TRUNK: 6363 END ---

; --- RCM-TRUNK: FAG4108 BEGIN ---
[FAG4108]
type=aor
contact=sip:192.168.99.170:5060
qualify_frequency=60
; --- RCM-TRUNK: FAG4108 END ---


[9999]
type=aor
max_contacts=9666
remove_existing=yes
qualify_frequency=60


[5858]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60

; --- RCM-TRUNK: UCM BEGIN ---
[UCM]
type=aor
contact=sip:192.168.99.5:5060
qualify_frequency=50
; --- RCM-TRUNK: UCM END ---

[2121]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60



[3001]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60


[555]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60


[10000]
type=aor
max_contacts=10
remove_existing=yes
qualify_frequency=60

