[support-queue]
musicclass = default          ; مزيكا الانتظار
strategy = rrmemory           ; يرن على الأعضاء واحد واحد (Round Robin)
timeout = 15                  ; بعد 15 ثانية لو محدش رد يحاول عضو تاني
retry = 5                     ; بعد 5 ثواني يعيد المحاولة
maxlen = 10                   ; أقصى عدد مكالمات في الانتظار
announce-frequency = 30       ; يقول كل 30 ثانية عن الوقت أو المكان في الطابور
announce-holdtime = yes       ; يقول الوقت التقريبي للانتظار
wrapuptime = 5                ; وقت راحة بسيط بعد المكالمة قبل استقبال مكالمة جديدة

; الأعضاء الثابتين (Static Agents)
member => PJSIP/2222
member => PJSIP/2233
