[support]
musicclass = default				; music in hold 
strategy = rrmemory
timeout = 5					;مده الرن عند كل ايجبت 
retry = 2					;الوقت الي بتقعده المكامله من الانتقال بين كل ايجنت 
maxlen = 10					;عدد الكلاينت الي فالكيو 
wrapuptime = 5					;وقت البريك لكل ايجنت بعد كل كول 
announce-holdtime = no
joinempty = yes
leavewhenempty = yes
autofill = no
monitor-type = MixMonitor			;تسجيل
;announce = RAFIK_Queuee			;دي رساله بيسمعها الايجنت الي رد علي الكالمه 
;queue-callerannounce = RAFIK_Queuee		;دي الرساله بيسمعها العميل اول لما الايجنت يرد عليه 
;autopause = yes
;=================================

;announce-frequency = 10			;رساله بيسمعها العميل كل 10 ثواني 
;periodic-announce=RAFIK_Queuee
;periodic-announce-frequency=5

;===================================

;reportholdtime = yes				; report hold time 
;queue-reporthold = RAFIK_Queuee		; رساله بيسمعها قبل قبل ميقوله ال هولد تايم
 
;===================================

;queue-thankyou = RAFIK_Queuee			; رساله بيسمعها الايجنت قبل ميسمع صوت العميل 

;===================================

;announce-position = yes				; كل شويه هتقولي اناترتيبي الكام فالمكالمه 
;announce-frequency = 5
;min-announce-frequency = 15
;===================================


setqueuevar = yes
;membergosub = qmember-setup,s,1



member => PJSIP/2121
member => PJSIP/2233





















;[general]
;persistentmembers = yes
;monitor-type = MixMonitor
;shared_lastcall=yes
;negative_penalty_invalid = no
;log_membername_as_agent = no
;force_longest_waiting_caller = no

;[markq]
;queue-callerannounce = you-are-being-connected
;strategy = ringall
;servicelevel = 60
;context = qoutcon
;penaltymemberslimit = 5
;timeout = 15
;maxlen = 0
;setinterfacevar=no
;setqueueentryvar=no
;setqueuevar=no
;membermacro=macro_name[,arg1[,...][,argN]]
;membergosub=gosub_context_name[,arg1[,...][,argN]]
;announce-frequency = 90
;min-announce-frequency = 15
;random-periodic-announce=no
;relative-periodic-announce=yes
;announce-holdtime = yes|no|once
;announce-position = yes
;announce-to-first-user = no
;announce-position-limit = 5
;announce-round-seconds = 10
;announce-position-only-up = yes
; queue-thankyou=;
;queue-youarenext = queue-youarenext
;queue-thereare	= queue-thereare
;queue-callswaiting = queue-callswaiting
;queue-quantity1 = queue-quantity1
;queue-quantity2 = queue-quantity2
;queue-holdtime = queue-holdtime
;queue-minute = queue-minute
;queue-minutes = queue-minutes
;queue-seconds = queue-seconds
;queue-thankyou = queue-thankyou
;queue-reporthold = queue-reporthold
;periodic-announce = queue-periodic-announce


; BEGIN RCM QUEUE GUI
[7772]
; RCM_NAME=teamtt
musicclass = default
strategy = random
timeout = 5
retry = 2
maxlen = 10
wrapuptime = 5
announce-position = no
announce-frequency = 15
reportholdtime = yes
joinempty = yes
leavewhenempty = yes
autofill = no
autopause = no
ringinuse = no
setqueuevar = yes
member => PJSIP/2121
member => PJSIP/5858

[7441]
; RCM_NAME=teamssssssssss
musicclass = hooold
strategy = rrmemory
timeout = 5
retry = 2
maxlen = 10
wrapuptime = 5
announce-position = no
announce-frequency = 15
reportholdtime = no
joinempty = yes
leavewhenempty = yes
autofill = no
autopause = no
ringinuse = no
setqueuevar = yes
periodic-announce = para
periodic-announce-frequency = 30
queue-callerannounce = para
announce = para
member => PJSIP/5858

[7008]
; RCM_NAME=uuuui
musicclass = hooold
strategy = rrmemory
timeout = 5
retry = 2
maxlen = 10
wrapuptime = 5
announce-position = no
announce-frequency = 15
reportholdtime = no
joinempty = yes
leavewhenempty = yes
autofill = no
autopause = yes
ringinuse = no
setqueuevar = yes
monitor-type = MixMonitor
member => PJSIP/555
member => PJSIP/2121
member => PJSIP/5000
; END RCM QUEUE GUI
